import Head from 'next/head'
import { FormEvent, useEffect , useRef} from 'react'


export default function Home() {
  const titleRef = useRef<HTMLInputElement>(null)

  const contentRef = useRef<HTMLInputElement>(null)

  useEffect(() =>{


  },[])

  const onSubmit = async (ev:FormEvent) =>{
    ev.preventDefault()
    console.log(titleRef.current?.value);
    console.log(contentRef.current?.value);

    const ourPerfectObject ={
      title: titleRef.current?.value ,
      content: contentRef.current?.value
    }

    const response = await fetch("./api/hello",{
      method: "POST",
      headers:{
        "content-type":"application/json",
      },
      body:JSON.stringify(ourPerfectObject)
    })
    const data = await response.json()
    console.log(data)
  }

  return (
    <>
      <Head>
        <title>this is a crud app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container flex justify-center pt-8 '>
       <form className='w-[400px] flex flex-col items-center p-2'>
        <input ref={titleRef} type="text" placeholder='title'  className='w-full h-[40px] rounded focus:outline-none'/>
        <input ref={contentRef} type="text" placeholder='content' className='w-full h-[40px] rounded focus:outline-none' />
        <button onClick={(ev:FormEvent) =>onSubmit(ev)}>
          submit
        </button>
       </form>
      </main>
    </>
  )
}
